openapi: 3.0.0
info:
  title: Servicio Ejemplo
  version: "1.0.0"
paths:
  /hello:
    get:
      summary: Saludo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
