name: Generaci贸n OpenAPI - Python Flask

on:
  push:
    branches:
      - main

jobs:
  generar-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generar c贸digo Python Flask desde api.yaml
        run: |
          echo "Archivos en el repositorio:"
          ls -la
          echo "Generando c贸digo a partir de api.yaml..."
          java -jar openapi-generator-cli.jar generate -i api.yaml -g python-flask -o ./openapi_server

      - name: Comprimir c贸digo generado
        run: |
          zip -r openapi_server.zip openapi_server

      - name: Subir artefacto generado (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: openapi_server_zip
          path: openapi_server.zip
